### ISSUE TITLE
Adding Social Media Buttons To Profile

### ISSUE THREAD

**Issue by Lukkie1998** [Fracture-Studios/FSForumOld#2]
Title says it all. Adding Buttons for: Skype, Steam, WAW, Youtube, Xfire, Facebook, Twitter (Not in this order). If you have any requests for buttons please respond on this issue.

**Comment by Lukkie1998** [comment]
Skype has been added.

**Comment by Lukkie1998** [comment]
Do we want the same Steam thing UGX uses, or do we just want it to be a single button on your profile?

**Comment by Ray1235** [comment]
A button on profile and Steam Overview on profile page

**Comment by Lukkie1998** [comment]
Added 8 Social Media Options, any recommendations are welcome!
